[project]
name = "fastapi-backend-course"
package-mode = false
version = "0.1.0"
description = ""
authors = [
    {name = "werden230",email = "rischicovec@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff (>=0.16.6,<0.17.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
